# Generated by Django 3.0.5 on 2020-05-26 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formapagamento',
            name='forma',
            field=models.CharField(max_length=75, unique=True, verbose_name='Forma de pagamento'),
        ),
    ]
