# Generated by Django 3.0.5 on 2020-05-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('Aguardando confirmação', 'Aguardando confirmação'), ('Pedido em produção', 'Pedido em produção'), ('Saiu para entrega', 'Saiu para entrega'), ('Entregue', 'Entregue')], default='Aguardando confirmação', max_length=70, verbose_name='Status do pedido'),
        ),
    ]
