# Generated by Django 3.0.5 on 2020-06-07 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200531_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinho',
            name='observacao',
            field=models.TextField(blank=True, default=None, max_length=75, null=True, verbose_name='Observação'),
        ),
    ]
