# Generated by Django 3.0.5 on 2020-06-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200607_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinho',
            name='observacao',
            field=models.TextField(blank=True, default='Sem observações', max_length=75, null=True, verbose_name='Observação'),
        ),
    ]
