# Generated by Django 3.0.5 on 2020-05-27 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_carrinho_cod_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinho',
            name='observacao',
            field=models.TextField(default=None, max_length=75, null=True, verbose_name='Observação'),
        ),
    ]
