# Generated by Django 3.0.5 on 2020-05-27 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200527_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='cod_cliente',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
